## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##

coreo_aws_advisor_alert "redshift-no-user-logging" do
  action :define
  service :redshift
  link "http://kb.cloudcoreo.com/mydoc_redshift-no-user-logging.html"
  display_name "Redshift user activity logging is disabled"
  description "Redshift user activity logging is disabled."
  category "Audit"
  suggested_action "Enable Redshift user activity logging."
  level "Warning"
  objectives ["cluster_parameter_groups", "cluster_parameters", "cluster_parameters"]
  call_modifiers [{}, {:parameter_group_name => "parameter_groups.parameter_group_name"}, {:parameter_group_name => "parameter_groups.parameter_group_name"}]
  id_map "modifiers.parameter_group_name"
  audit_objects ["", "parameters.parameter_name", "parameters.parameter_value"]
  operators ["", "==", "=="]
  alert_when ["", "enable_user_activity_logging", false]
end

coreo_aws_advisor_redshift "advise-redshift" do
  action :advise
  alerts ["redshift-no-user-logging"]
end

coreo_uni_util_notify "send-email" do
  action :notify
  type 'email'
  allow_empty true
  send_on "always"
  payload "COMPOSITE::coreo_aws_advisor_redshift.advise-redshift.report"
  payload_type "json"
  endpoint ({
      :to => 'paul@cloudcoreo.com', :subject => 'test alert'
  })
end
